---
# tasks file for roles/web-app-role
- name: log into docker hub registry
  docker_login:
        email: "ship.romeo@gmail.com"
        username: "yurgent"
        password: "{{ dockerhub_pass }}"

- name: create docker network
  become: true
  become_method: sudo
  docker_network:
    name: containers_net
    state: present

- name: launch 1st container on port 5021
  docker_container:
    name: web-app-1
    hostname: web-app-1
    state: started
    image: "yurgent/epam:web_app"
    pull: true
    ports:
      - "5021:5000"
    networks:
      - name: containers_net

- name: launch 2nd container on port 5022
  docker_container:
    name: web-app-2
    hostname: web-app-2
    state: started
    image: "yurgent/epam:web_app"
    pull: true
    ports:
      - "5022:5000"
    networks:
      - name: containers_net

- name: launch 3rd container on port 5023
  docker_container:
    name: web-app-3
    hostname: web-app-3
    state: started
    image: "yurgent/epam:web_app"
    pull: true
    ports:
      - "5023:5000"
    networks:
      - name: containers_net

